hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=none
hibernate.connection.provider_class=org.hibernate.hikaricp.internal.HikariCPConnectionProvider

# HikariCP Settings
hibernate.hikari.dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
hibernate.hikari.dataSource.url=jdbc:postgresql://localhost:5432/reservation_app_db
hibernate.hikari.dataSource.user=postgres
hibernate.hikari.dataSource.password=1234
hibernate.hikari.maximumPoolSize=10